# Generated by Django 4.0.3 on 2022-03-30 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='shorturl',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
